name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build Docker images
      uses: docker/bake-action@v4
      with:
        pull: true
        load: true
        files: |
          tests-server/compose.yaml
        set: |
          *.cache-from=type=gha,scope=${{github.ref}}
          *.cache-from=type=gha,scope=refs/heads/main
          *.cache-to=type=gha,scope=${{github.ref}},mode=max
    -
      name: Start services
      run: docker compose up --wait --no-build
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
